### ISSUE TITLE
解密问题

### ISSUE THREAD

**Issue by daisutao** [tan00/gmssl_cipher_tool#1]
解密时，崩溃不是你的问题，而是GmSSL中一个函数的问题。
GmSSL要说也是一个大牌了，不知道为什么还有这么一个低级的问题。

**Comment by tan00** [comment]
周末抽空跟踪一下。  请问是GMSSL哪里有问题？

**Comment by daisutao** [comment]
在sm2oct.c中，函数o2i_SM2CiphertextValue返回一个空指针。
这就是我一直不想用国人写的东西的原因。你都不知道是你的问题，还是库的问题。
openssl1.1.1中支持sm2了，但是没有例子，根本不知道怎么用。没有办法，才使用这个。

**Comment by daisutao** [comment]
你的代码我修改了好多，怎么发给你?

**Comment by tan00** [comment]
> 你的代码我修改了好多，怎么发给你?

发起 pull request

**Comment by tan00** [comment]
已修复.
